config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "tweets#index"
  resources :tweets do
  	resources :likes, only: [] do
      post :toggle, on: :collection
    end
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :likes, as: :likeable, dependent: :destroy
  has_one :comment, as: :commentable, dependent: :destroy

  def liked?(user_id)
    Like.where(user_id: user_id, likeable_id: id, likeable_type: self.class.name).exists?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_one_attached :attachment do |attachable|
    attachable.variant :thumb, resize: '100x100'
  end
  validates :title, presence: true, length: { minimum: 5 }
  validates :content, presence: true
  enum status: { draft: 0, publish: 1, remove: 2 }

  def liked?(user_id)
    Like.where(user_id: user_id, likeable_id: id, likeable_type: self.class.name).exists?
  end

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  enum role: [:default, :author, :admin]
  after_initialize :set_default_role, :if => :new_record?
  has_many :tweets

  def set_default_role
    self.role ||= :default
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_commentable

  def index
    @comments = @commentable.comments
  end

  def new
    @comment = @commentable.comments.new
  end

  def create
    @comment = @commentable.comments.create(comments_params)
  end

  private

  def load_commentable
    klass = [Tweet, Comment].detect { |c| params["#{c.name.underscore}_id"] }
    @commentable = klass.find(params["#{klass.name.underscore}_id"])
  end

  def comments_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :load_likeable

  def toggle
    like = @likeable.likes.find_or_initialize_by(user_id: current_user.id)
    @result = like.persisted? ? like.destroy : like.save
  end

  private

  def load_likeable
    klass = [Tweet, Comment].detect { |c| params["#{c.name.underscore}_id"] }
    @likeable = klass.find(params["#{klass.name.underscore}_id"])
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @tweets = Tweet.includes(:user).all
  end

  def show
    @commentable = @tweet
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def new
    @tweet = current_user.tweets.new
  end

  def edit
    return unless @tweet.draft?
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.'}
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.'}
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:title, :content, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_comment.html.erb
<div class="col-3 col-sm-2 col-lg-3 px-3 px-md-4 pl-lg-3 pr-lg-2">
    <%= image_tag 'white.png', class: 'img-fluid border circle-border' %>
</div>
<div class="col-9 col-sm-10 col-lg-9 pl-0 align-self-center pr-4" id="comment_<%= comment.id %>">
    <p class="text-sm grey-text">
        <%= comment.body %>
    </p>
    <p class="text-sm text-right grey-text font-weight-bold mb-0">
        - <%= comment.user.name %>
    </p>
</div>
<hr class="my-0">

app/views/comments/_comments.html.erb
<div class="card-body bg-white comment-container os-theme-black p-0">
  <% @comments.each do |comment| %>
    <div class="row p-2">
      <%= render 'comments/comment', comment: comment %>
    </div>
  <% end %>
  <div class="row p-2" id="addedComments">
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@commentable, @comment] do |form| %>
  <%= form.hidden_field :user_id, currnt_user.id %>
  <%= form.text_field :body %>
  <%= form.submit : save %>
<% end %>

app/views/comments/create.js.erb
$('#addedComments').append("<%= j render 'comments/comment', comment: @comment %>")
$('#commentBody').val('')

app/views/comments/new.html.erb
<%= render 'form' %>
<%= link_to "Add Comment", challenge_idea_comments_path(challenge_id: @challenge.id, idea_id: @idea.id), method: :post, remote: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Log In", new_user_session_path %>
    <% else %>
      <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/toggle.js.erb
$('#likeToggle').toggleClass("fa-thumbs-up fa-thumbs-o-up");
if ("<%= @result %>" === 'true'){
  $('#likesCount').text(Number($('#likesCount').text())+1);
}
else
{
  $('#likesCount').text(Number($('#likesCount').text())-1);
}

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>
<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.title %></td>
        <td><%= tweet.content %></td>
        <td><%= tweet.user.name %></td>
        <td><%= link_to 'Show', tweet %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>
<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tweet.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.content %>
</p>

<p>
  <strong>Author:</strong>
  <%= @tweet.user.name %>
</p>

<p>
  <strong>Likes:</strong>
  <%= link_to toggle_tweet_likes_path(tweet_id: @tweet.id), method: :post, remote: true, class: 'btn btn-circle pink-ghost-btn mr-3' do %>
    <i class="fa <%= @tweet.liked?(current_user) ? 'fa-thumbs-up': 'fa-thumbs-o-up' %>" id='likeToggle'></i>
  <% end %>
  <div id='likesCount'>
    <%= @tweet.likes.count %>
  </div>
</p>

<%= image_tag(@tweet.attachment) if @tweet.attachment %>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

<h5 class="font-weight-black px-3 py-2"><%= @comments.count%> Comments</h5>
<%= render 'comments/comments' %>
<%if user_signed_in? %>
  <div class="rounded-sm-bottom border-0 bg-white px-2">
    <div class="row">
      <div class="col-3 col-sm-2 col-lg-3 px-3 px-md-4 pl-lg-3 pr-lg-2">
        <%= image_tag 'white.png', class: 'img-fluid border circle-border' %>
      </div>
      <div class="col-9 col-sm-10 col-lg-9 pl-0 align-self-center pr-4">
        <%= form_for [@commentable, @comment], remote: true do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.text_area :body, id: 'commentBody', class:'form-control form-control-sm border rounded-0', rows:"2", placeholder:"Give your opinion on the tweet.", required: true %>
          <%= f.submit :post %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>